name: taaruf_
description: "A fresh start for the Taaruf app."

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1 
  google_fonts: ^5.0.0
  intl_phone_field: ^3.0.0

 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/intro1.png
    - assets/images/intro2.png
    - assets/images/intro3.png
    - assets/images/headsign.png
    - assets/images/lebanon.png
    - assets/images/logo.png
    
